# 9장 취소

코틀린 코루틴에서 아주 중요한 기능 중 하나는 바로 취소 입니다.

## 기본적인 취소

Job 인터페이스는 취소하게 하는 cancel 메소드를 가지고 있습니다. cancel 메소드를 호출하면 다음 효과를 확인할 수 있습니다.
* 호출한 코루틴은 첫 번쨰 중단점에서 잡을 끝냅니다.
* 잡이 자식을 가지고 있다면, 그들 또한 취소됩니다. 하지만 부모는 영향 받지 않습니다.
* 잡이 취소되면, 취소된 잡은 새로운 코루틴의 부모로 사용될 수 없습니다.

```Kotlin
suspend fun main() {
    coroutineScope {
        val job = launch {
            repeat(1000){
                delay(200)
                println("I'm sleeping $it ...")
            }
        }

        delay(1100)
        job.cancel()
        job.join()
        println("main: Now I can quit.")
    }
}
I'm sleeping 0 ...
I'm sleeping 1 ...
I'm sleeping 2 ...
I'm sleeping 3 ...
I'm sleeping 4 ...
main: Now I can quit.
```

Job의 cancel 함수를 호출할 때 취소 이유를 명시하기 위해 CancellationException의 하위타입을 사용해야합니다.

## 취소 중 코루틴을 한 번 더 호출하기

코루틴이 실제 종료되기 전에 CancellationException을 잡고 후처리와 같은 좀더 많은 연산을 수행할 수 있습니다.
하지만 앞서 코루틴이 종료되면 부모 코루틴이 될 수 없다는 말 기억하시나요? 그렇다면 어떻게 코루틴이 취소된 두 중단함수를 다시 호출할 수 있을까요? 이런 경우 withContext 함수를 많이 사용합니다.

```Kotlin
suspend fun main() {
    coroutineScope {
        val job = launch {
            try{
                delay(200)
                println("job: I'm running.")
            }finally {
                println("finally: I'm running.")
                withContext(NonCancellable){
                    delay(1000)
                    println("clean up")
                }
            }
        }

        delay(100)
        job.cancelAndJoin()
        println("main: Now I can quit.")
    }
}
```

후처리를 위해 사용한 또 다른 방법으로는 Job의 invokeOnCompletion 메소드를 호출하는 것입니다.

invokeOnCompletion은 잡이 Completed, Cancelled 일 때 호출될 핸들러를 지정하는 역할을 합니다.

```Kotlin
suspend fun main() {
    coroutineScope {
        val job = launch {
            delay(1000)
        }

        job.invokeOnCompletion { exception ->
            println("job completed with exception: $exception")
        }

        delay(400)
        job.cancelAndJoin()
        println("main: Now I can quit.")
    }
}
job completed with exception: kotlinx.coroutines.JobCancellationException: StandaloneCoroutine was cancelled; job=StandaloneCoroutine{Cancelled}@20b814b8
main: Now I can quit.
```

invokeOnCompletion에 지정하는 헨들러의 파라미터 중 하나인 예외의 종류는 다음과 같습니다.
* 잡이 예외 없이 끝나면 null이 됩니다.
* 코루틴이 취소되었으면 CancellationException이 됩니다.
* 코루틴을 종료시킨 예외일 수 있습니다.

## 중단될 수 없는 걸 중단하기

취소는 중단점에서 발생함을 명심해야합니다. 따라서 중단점이 없다면 취소를 할 수 없습니다. 이는 delay대신 Thread.slepp을 호출할 때 발생합니다.

```Kotlin
suspend fun main() {
    coroutineScope {
        val job = Job()
        launch(job) {
            repeat(1000){
                Thread.sleep(200)
                println("I'm sleeping $it ...")
            }
        }
        delay(1100)
        job.cancelAndJoin()
        println("main: Now I can quit.")
    }
}
```

위 코드는 1초면 종료될거라 예상하지만, 그와 반대로 3분 넘게 지속됩니다. 이런 문제는 어떻게 해결할 수 있을까요?

코루틴에서는 yield 메소드를 통해 코루틴을 중단하고 재실행할 수 있는 중단점을 제공합니다.(이는 cpu 집약적 로직에서 중간에 다른 코루틴이 실행될 수 있도록 할 수 있습니다.)

또 다른 방법은 잡의 상태를 추적하는 것입니다.
코루틴 내부에서 this(리시버)는 빌더의 스코프를 참조할 수 있습니다.

CoroutineScope는 coroutineContext 프로퍼티를 사용해 참조할 수 있는 컨텍스트를 가지고 있습니다. 또한 잡은 코루틴이 활성 상태인지 확인할 수 있는 함수를 제공합니다.

```Kotlin
suspend fun main() {
    coroutineScope {
        val job = Job()
        launch(job) {
            do{
                Thread.sleep(200)
                println("I'm still working...")
            }while (isActive)
        }
        delay(1100)
        job.cancelAndJoin()
        println("main: Now I can quit.")
    }
}
```

isActive 이외에 잡이 활성 상태가 아니면 CancellationException을 발생시키는 ensureActive()함수를 통해서도 중단할 수 있습니다.

```Kotlin
suspend fun main() {
    coroutineScope {
        val job = Job()
        launch(job) {
            repeat(1000) { i ->
                Thread.sleep(200)
                ensureActive()
                println("job: I'm sleeping $i ...")
            }
        }
        delay(1100)
        job.cancelAndJoin()
        println("main: Now I can quit.")
    }
}
```
